# application.yaml
spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}  # 환경변수가 없으면 local
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
springdoc:
  swagger-ui:
    path: /swagger/swagger-ui
  api-docs:
    path: /swagger/swagger-docs
