# application-prod
spring:
  sql:
    init:
      mode: never
  config:
    activate:
      on-profile: prod

  datasource:
    hikari:
      max-lifetime: 600000        # 10분 (기본값 30분에서 단축)
      connection-timeout: 20000   # 20초
      idle-timeout: 300000        # 5분
      validation-timeout: 5000    # 5초
      leak-detection-threshold: 60000  # 1분
    url: ${POSTGRE_DB_URL}
    username: ${POSTGRE_DB_USERNAME}
    password: ${POSTGRE_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

    data:
      mongodb:
        uri: ${MONGO_URI}
fastapi:
  base-url: ${FASTAPI_URL}
  timeout: 30000

# 운영 환경 전용 설정
admin:
  default:
    email: ${ADMIN_EMAIL:admin@gnavi.com}
    password: ${ADMIN_PASSWORD:}  # 환경변수에서 주입
    name: ${ADMIN_NAME:Growth Navigator 관리자}

data:
  initialization:
    enabled: ${DATA_INIT_ENABLED:false}  # 운영에서는 기본 비활성화
    mode: ${DATA_INIT_MODE:minimal}      # 최소한의 데이터만