# application.yaml
spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}  # 환경변수가 없으면 local
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  task:
    execution:
      pool:
        core-size: 2
        max-size: 4
        queue-capacity: 100
      thread-name-prefix: thumbnail-
    scheduling:
      pool:
        size: 2
springdoc:
  swagger-ui:
    path: /swagger/swagger-ui
  api-docs:
    path: /swagger/swagger-docs

app:
  storage:
    pvc:
      path: ${APP_STORAGE_PVC_PATH:/mnt/gnavi}
    base-url: ${APP_STORAGE_BASE_URL}