# application-prod
spring:
  sql:
    init:
      mode: never
  config:
    activate:
      on-profile: prod

  datasource:
    url: ${POSTGRE_DB_URL}
    username: ${POSTGRE_DB_USERNAME}
    password: ${POSTGRE_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  data:
    mongodb:
      uri: ${MONGO_URI}
#fastapi:
#  base-url: ${FASTAPI_BASE_URL}
#  endpoints:
#    chat-room-create: /ai/room/c