spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:postgresql://localhost:5432/gnavidb
    username: gnavi_user
    password: gnavipwd
    driver-class-name: org.postgresql.Driver
  data:
    mongodb:
      host: localhost
      port: 27017
      database: gnavi
# FastAPI 설정 (환경변수 사용)
fastapi:
  base-url: ${FASTAPI_BASE_URL:http://localhost:8001}  # 기본값: 로컬 FastAPI
  timeout: ${FASTAPI_TIMEOUT:30000}

# 로컬 환경 전용 설정
admin:
  default:
    email: "admin@local.com"
    password: "local123"
    name: "로컬 관리자"

data:
  initialization:
    enabled: true  # 로컬에서는 목업 데이터 생성
    mode: full     # 전체 목업 데이터