apiVersion: apps/v1
kind: Deployment
metadata:
  name: gnavi4-backend
  namespace: sk-team-04
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gnavi4-backend
  template:
    metadata:
      labels:
        app: gnavi4-backend
    spec:
      serviceAccountName: default
      containers:
        - name: webserver
          image: amdp-registry.skala-ai.com/skala25a/sk-gnavi4-be:latest
          imagePullPolicy: Always
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: NAMESPACE
              value: sk-team-04
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: prod-db-secret
                  key: POSTGRE_DB_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: prod-db-secret
                  key: POSTGRE_DB_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: prod-db-secret
                  key: POSTGRE_DB_PASSWORD
            - name: SPRING_DATA_MONGODB_URI  # 이름 변경!
              valueFrom:
                secretKeyRef:
                  name: prod-db-secret
                  key: MONGO_URI
            - name: FASTAPI_URL
              valueFrom:
                secretKeyRef:
                  name: prod-db-secret
                  key: FASTAPI_URL
            # 관리자 계정 설정
            - name: ADMIN_EMAIL
              valueFrom:
                secretKeyRef:
                  name: prod-db-secret
                  key: ADMIN_EMAIL
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: prod-db-secret
                  key: ADMIN_PASSWORD
            - name: ADMIN_NAME
              value: "Grow Navigator 관리자"

              # 데이터 초기화 설정 (새로 추가)
            - name: DATA_INIT_ENABLED
              value: "true"  # 운영 환경에서도 최소 데이터 생성
            - name: DATA_INIT_MODE
              value: "minimal"  # 최소한의 데이터만

              # PVC 설정
            - name: APP_STORAGE_PVC_PATH
              value: "/data"
            - name: APP_STORAGE_BASE_URL
              value: "https://sk-gnavi4.skala25a.project.skala-ai.com"
          # 볼륨 마운트
          volumeMounts:
            - name: storage-volume
              mountPath: /data

      volumes:
        - name: storage-volume
          persistentVolumeClaim:
            claimName: efs-sc-gnavi4-backend
