apiVersion: apps/v1
kind: Deployment
metadata:
  name: gnavi4-backend
  namespace: sk-team-04
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gnavi4-backend
  template:
    metadata:
      labels:
        app: gnavi4-backend
    spec:
      serviceAccountName: default
      containers:
        - name: webserver
          image: amdp-registry.skala-ai.com/skala25a/sk-gnavi4-be:32-f40bc562494a
          imagePullPolicy: Always
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: prod
            - name: NAMESPACE
              value: sk-team-04
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: prod-db-secret
                  key: POSTGRE_DB_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: prod-db-secret
                  key: POSTGRE_DB_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: prod-db-secret
                  key: POSTGRE_DB_PASSWORD
            - name: SPRING_DATA_MONGODB_URI  # 이름 변경!
              valueFrom:
                secretKeyRef:
                  name: prod-db-secret
                  key: MONGO_URI
