apiVersion: apps/v1
kind: Deployment
metadata:
  name: gnavi4-backend
  namespace: sk-team-04
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gnavi4-backend
  template:
    metadata:
      labels:
        app: gnavi4-backend
    spec:
      serviceAccountName: default
      containers:
        - name: webserver
          image: amdp-registry.skala-ai.com/skala25a/sk-gnavi4-be@sha256:c90bb9231cbbe94e9ada06ed76ddcd7712aea6beb43411fca48feb8e32412e2d
          imagePullPolicy: Always
          env:
            - name: LOGGING_LEVEL_ROOT
              value: DEBUG
            - name: NAMESPACE
              value: sk-team-04
            - name: SPRING_DB_HOST
              valueFrom:
                secretKeyRef:
                  name: prod-db-secret
                  key: POSTGRE_HOST
            - name: SPRING_DB_HOST
              valueFrom:
                secretKeyRef:
                  name: prod-db-secret
                  key: POSTGRE_HOST
            - name: SPRING_DB_HOST
              valueFrom:
                secretKeyRef:
                  name: prod-db-secret
                  key: POSTGRE_HOST
            - name: SPRING_DB_HOST
              valueFrom:
                secretKeyRef:
                  name: prod-db-secret
                  key: POSTGRE_HOST
            - name: SPRING_DB_HOST
              valueFrom:
                secretKeyRef:
                  name: prod-db-secret
                  key: POSTGRE_HOST