apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-sc-gnavi4
  namespace: sk-team-04
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
  storageClassName: efs-sc-shared
