--
name: Build, Push Docker & Update deploy.yaml

on:
  push:
    branches: [ "main" ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    env:
      IMAGE_REGISTRY: ${{ secrets.IMAGE_REGISTRY }}
      IMAGE_NAME: ${{ secrets.IMAGE_NAME }}
      IMAGE_TAG: "1.0.0"
      GIT_BRANCH: "main"
      DEPLOY_FILE: "k8s/deploy.yaml"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle (test 제외)
        run: ./gradlew clean build -x test

      - name: Generate final image tag
        id: image_tag
        run: |
          HASH=$(date +%s%N | sha256sum | cut -c1-12)
          TAG="${{ env.IMAGE_TAG }}-${{ github.run_number }}-${HASH}"
          echo "FINAL_IMAGE_TAG=$TAG" >> $GITHUB_ENV
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Docker Login to Harbor
        run: echo "${{ secrets.HARBOR_PASSWORD }}" | docker login ${{ secrets.IMAGE_REGISTRY }} -u ${{ secrets.HARBOR_USERNAME }} --password-stdin

      - name: Docker Build & Push
        run: |
          FULL_IMAGE=${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.FINAL_IMAGE_TAG }}
          docker build -t $FULL_IMAGE --platform linux/amd64 .
          docker push $FULL_IMAGE

      - name: Update deploy.yaml image tag
        run: |
          sed -i 's|^[[:space:]]*image:.*$|          image: '"${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.FINAL_IMAGE_TAG }}"'|g' $DEPLOY_FILE
          echo "Updated $DEPLOY_FILE:"
          cat $DEPLOY_FILE

      - name: Commit and push updated deploy.yaml
        env:
          GIT_USER_NAME: ${{ secrets.GIT_USER_NAME }}
          GIT_USER_EMAIL: ${{ secrets.GIT_USER_EMAIL }}
          GIT_PUSH_TOKEN: ${{ secrets.GIT_PUSH_TOKEN }}
        run: |
          git config user.name "$GIT_USER_NAME"
          git config user.email "$GIT_USER_EMAIL"
          git add $DEPLOY_FILE || true
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "[AUTO] Update deploy.yaml with image ${{ env.FINAL_IMAGE_TAG }}"
            git remote set-url origin https://${GIT_PUSH_TOKEN}@github.com/${{ github.repository }}
            git push origin ${{ env.GIT_BRANCH }}
          fi
