---
name: Build and Push to Harbor
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: temurin
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build Spring Boot project
        run: ./gradlew bootJar
      - name: Docker Login to Harbor
        run: echo "${{ secrets.HARBOR_PASSWORD }}" | docker login ${{ secrets.HARBOR_URL
          }} -u ${{ secrets.HARBOR_USERNAME }} --password-stdin
      - name: Build Docker image
        run: >
          IMAGE=${{ secrets.HARBOR_URL }}/${{ secrets.HARBOR_PROJECT }}/${{
          secrets.IMAGE_NAME }}:latest

          docker build -t $IMAGE .

          echo "Built Docker image: $IMAGE"
      - name: Push Docker image to Harbor
        run: >
          IMAGE=${{ secrets.HARBOR_URL }}/${{ secrets.HARBOR_PROJECT }}/${{
          secrets.IMAGE_NAME }}:latest

          docker push $IMAGE
  dependency-submission:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: temurin
      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@v4.0.0
